# site settings
title: Tatevik
subtitle: by FASHION DRUG
email: tatevikpoghosyan0104@gmail.com
description: "Fashion you can buy, but style you possess. The key to style is learning who you are, which takes years. There's no how-to road map to style. It's about self expression and, above all, attitude." —Iris Apfel
baseurl: "/my-portfolio-jekyll" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: Kocamustafapasa neighborhood, Fatih district,
city: Istanbul
state: 
zip_code: 34098
country: Turkey
phone: +90 (537) 050 76 52

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url: https://www.facebook.com/tatevik.poghosyan.1/
github_url: https://github.com/poghosyantatevik
gitlab_url: 
googleplus_url: 
instagram_url: https://www.instagram.com/poghosyan_tatevik/?hl=en
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
